version: '3.9'
services:

  primereando:
    # default port 9000 (FastCGI)
    image: wordpress:php8.1-fpm-alpine
    container_name: wp-wordpress-primereando
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - database
    volumes:
      - ${WORDPRESS_PRIMEREANDO_HOME}:/opt/primereando
      - ${WORDPRESS_UPLOADS_CONFIG_MEMORY_256}:/usr/local/etc/php/conf.d/uploads.ini
      # - /path/to/repo/myTheme/:/var/www/html/wp-content/themes/myTheme
    working_dir: /opt/primereando
    environment:
      - WORDPRESS_DB_HOST=$WORDPRESS_DB_HOST
      - WORDPRESS_DB_NAME=primereando
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}

#  lrdp:
#    # default port 9000 (FastCGI)
#    image: wordpress:php7.4-fpm-alpine
#    container_name: wp-wordpress-lrdp
#    env_file:
#      - .env
#    restart: unless-stopped
#    networks:
#      - wordpress
#    depends_on:
#      - database
#    volumes:
#      - ${WORDPRESS_LRDP_HOME}:/opt/lrdp
#      - ${WORDPRESS_UPLOADS_CONFIG_MEMORY_128}:/usr/local/etc/php/conf.d/uploads.ini
#      # - /path/to/repo/myTheme/:/var/www/html/wp-content/themes/myTheme
#    working_dir: /opt/lrdp
#    environment:
#      - WORDPRESS_DB_HOST=$WORDPRESS_DB_HOST
#      - WORDPRESS_DB_NAME=lrdp
#      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
#      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}

#  infovirales:
#    # default port 9000 (FastCGI)
#    image: wordpress:php7.4-fpm-alpine
#    container_name: wp-wordpress-infovirales
#    env_file:
#      - .env
#    restart: unless-stopped
#    networks:
#      - wordpress
#    depends_on:
#      - database
#    volumes:
#      - ${WORDPRESS_INFOVIRALES_HOME}:/opt/infovirales
#      - ${WORDPRESS_UPLOADS_CONFIG_MEMORY_128}:/usr/local/etc/php/conf.d/uploads.ini
      # - /path/to/repo/myTheme/:/var/www/html/wp-content/themes/myTheme
#    working_dir: /opt/infovirales
#    environment:
#      - WORDPRESS_DB_HOST=$WORDPRESS_DB_HOST
#      - WORDPRESS_DB_NAME=infovirales
#      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
#      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}

#  analogiasconsultora:
#    # default port 9000 (FastCGI)
#    image: wordpress:php8.1-fpm-alpine
#    container_name: wp-wordpress-analogias
#    env_file:
#      - .env
#    restart: unless-stopped
#    networks:
#      - wordpress
#    depends_on:
#      - database
#    volumes:
#      - ${WORDPRESS_ANALOGIAS_HOME}:/opt/analogiasconsultora
#      - ${WORDPRESS_UPLOADS_CONFIG_MEMORY_32}:/usr/local/etc/php/conf.d/uploads.ini
#      # - /path/to/repo/myTheme/:/var/www/html/wp-content/themes/myTheme
#    working_dir: /opt/analogiasconsultora
#    environment:
#      - WORDPRESS_DB_HOST=$WORDPRESS_DB_HOST
#      - WORDPRESS_DB_NAME=analogias
#      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
#      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}


##Mañana revisar que esto no va
#  spartanit:
#    # default port 9000 (FastCGI)
#    image: wordpress:php7.4-fpm-alpine
#    container_name: wp-wordpress-infovirales
#    env_file:
#      - .env
#    restart: unless-stopped
#    networks:
#      - wordpress
#    depends_on:
#      - database
#    volumes:
#      - ${WORDPRESS_INFOVIRALES_HOME}:/var/www/html
#      - ${WORDPRESS_UPLOADS_CONFIG}:/usr/local/etc/php/conf.d/uploads.ini
#      # - /path/to/repo/myTheme/:/var/www/html/wp-content/themes/myTheme
#    working_dir: /opt/infovirales
#    environment:
#      - WORDPRESS_DB_HOST=$WORDPRESS_DB_HOST
#      - WORDPRESS_DB_NAME=infovirales
#      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
#      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}

  database:
    # default port 3306
    image: mariadb
    container_name: database
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - wordpress
    environment:
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=rootpassword123!
      - MYSQL_TCP_PORT:3306
#    ports:
#      - "3306:3306"    # http
    volumes:
      - ${MYSQL_LOCAL_HOME}:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command:
      - '--default-authentication-plugin=mysql_native_password'

  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:alpine
    container_name: wp-nginx
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - primereando
#      - lrdp
      - infovirales
#      - analogiasconsultora
    ports:
      - "80:80"    # http
      - "443:443"   # https
    volumes:
#      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
#      - ${NGINX_CONF_SITE1}:/etc/nginx/conf.d/default.conf
      - ${WORDPRESS_PRIMEREANDO_HOME}:/opt/primereando
      - ${WORDPRESS_INFOVIRALES_HOME}:/opt/infovirales
#      - ${WORDPRESS_LRDP_HOME}:/opt/lrdp
#      - ${WORDPRESS_ANALOGIAS_HOME}:/opt/analogiasconsultora
#      - ${WORDPRESS_SPARTANIT_HOME}:/opt/Spartanit
      - ${NGINX_CONF_SITE1}:/etc/nginx/conf.d/primereando.conf
      - ${NGINX_CONF_SITE2}:/etc/nginx/conf.d/infovirales.conf
#      - ${NGINX_CONF_SITE3}:/etc/nginx/conf.d/lrdp.conf
#      - ${NGINX_CONF_SITE4}:/etc/nginx/conf.d/analogiasconsultora.conf
#      - ${NGINX_CONF_SITE5}:/etc/nginx/conf.d/spartanit.conf
      - ${NGINX_SSL_CERTS}:/etc/ssl:ro
      - ${NGINX_LOGS}:/var/log/nginx

  # adminer - bring up only as needed - bypasses nginx
  adminer:
#    # default port 8080
    image: adminer:4
    container_name: wp-adminer
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - database
    ports:
      - "9000:8080"

networks:
  wordpress:
    name: wp-wordpress
    driver: bridge